SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `AdminMst` (
  `AdminUserID` INT AUTO_INCREMENT NOT NULL,
  `password` VARCHAR(50) NULL,
  `status` TINYINT(1) NULL,
  `userName` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`AdminUserID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `AgentMst` (
  `ID` INT AUTO_INCREMENT NOT NULL,
  `login_id` VARCHAR(50) NULL,
  `pwd` VARCHAR(50) NULL,
  `name` VARCHAR(50) NULL,
  `email` VARCHAR(50) NULL,
  `pan` VARCHAR(50) NULL,
  `gstno` VARCHAR(50) NULL,
  `account` VARCHAR(50) NULL,
  `ifsc` VARCHAR(50) NULL,
  `status` INT NULL,
  `MobileNumber` BIGINT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `IpWhitelistMst` (
  `WhitelistIPId` INT AUTO_INCREMENT NOT NULL,
  `WhitelistIP` VARCHAR(100) NULL,
  `UserID` INT NULL,
  `Created_On` DATETIME NULL,
  `Upated_On` DATETIME NULL,
  `Status` INT NULL,
  PRIMARY KEY (`WhitelistIPId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `MONEY_TRANSFER_PAYIN` (
  `TRANSACTIONID` BIGINT AUTO_INCREMENT NOT NULL,
  `REFERENCE_NUMBER` VARCHAR(50) NULL,
  `SERVICE_NAME` VARCHAR(50) NOT NULL,
  `AMOUNT` DECIMAL(18, 2) NOT NULL,
  `TAX` DECIMAL(18, 2) NOT NULL,
  `TAX_AMOUNT` DECIMAL(18, 2) NOT NULL,
  `TOTAL_AMOUNT` DECIMAL(18, 2) NOT NULL,
  `AccountNo` BIGINT NOT NULL,
  `MobileNo` BIGINT NOT NULL,
  `BENEFICIAL_ID` VARCHAR(20) NULL,
  `STATUS` VARCHAR(50) NULL,
  `CREATED_ON` DATETIME NOT NULL,
  `CREATED_BY` INT NOT NULL,
  `UPDATED_ON` DATETIME NULL,
  `UPDATED_BY` VARCHAR(50) NULL,
  `UPDATE_REMARK` VARCHAR(50) NULL,
  `ServiceVendor` VARCHAR(100) NULL,
  `PortalName` VARCHAR(50) NULL,
  `REQUEST_IP_ADDRESS` VARCHAR(50) NULL,
  `UPDATE_IP_ADDRESS` VARCHAR(50) NULL,
  `REMARKS` VARCHAR(100) NULL,
  `ModOfPayment` VARCHAR(50) NULL,
  `user_order_id` VARCHAR(150) NULL,
  `BankName` VARCHAR(50) NULL,
  `IFSC` VARCHAR(50) NULL,
  `HolderName` VARCHAR(100) NULL,
  `Total_CD_Amt` VARCHAR(100) NULL,
  `UTR` VARCHAR(50) NULL,
  `REASON` VARCHAR(1000) NULL,
  `TrFrom` VARCHAR(5) NULL,
  `TRSID` VARCHAR(15) NULL,
  `TRUpdated` INT NULL,
  `UpdatedBalance` INT NULL,
  PRIMARY KEY (`TRANSACTIONID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=1000000000;

CREATE TABLE `MONEY_TRANSFER_PAYOUT` (
  `TRANSACTIONID` BIGINT AUTO_INCREMENT NOT NULL,
  `REFERENCE_NUMBER` VARCHAR(50) NULL,
  `SERVICE_NAME` VARCHAR(50) NOT NULL,
  `AMOUNT` DECIMAL(18, 2) NOT NULL,
  `TAX` DECIMAL(18, 2) NOT NULL,
  `TAX_AMOUNT` DECIMAL(18, 2) NOT NULL,
  `TOTAL_AMOUNT` DECIMAL(18, 2) NOT NULL,
  `AccountNo` BIGINT NOT NULL,
  `MobileNo` BIGINT NOT NULL,
  `BENEFICIAL_ID` VARCHAR(20) NULL,
  `STATUS` VARCHAR(50) NULL,
  `CREATED_ON` DATETIME NOT NULL,
  `CREATED_BY` INT NOT NULL,
  `UPDATED_ON` DATETIME NULL,
  `UPDATED_BY` VARCHAR(50) NULL,
  `UPDATE_REMARK` VARCHAR(50) NULL,
  `ServiceVendor` VARCHAR(100) NULL,
  `PortalName` VARCHAR(50) NULL,
  `REQUEST_IP_ADDRESS` VARCHAR(50) NULL,
  `UPDATE_IP_ADDRESS` VARCHAR(50) NULL,
  `REMARKS` VARCHAR(100) NULL,
  `ModOfPayment` VARCHAR(50) NULL,
  `user_order_id` VARCHAR(150) NULL,
  `BankName` VARCHAR(50) NULL,
  `IFSC` VARCHAR(50) NULL,
  `HolderName` VARCHAR(100) NULL,
  `Total_CD_Amt` VARCHAR(100) NULL,
  `UTR` VARCHAR(50) NULL,
  `REASON` VARCHAR(1000) NULL,
  `ActivePayout` INT NULL,
  PRIMARY KEY (`TRANSACTIONID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=100000;

CREATE TABLE `Notifications` (
  `NotificationID` INT AUTO_INCREMENT NOT NULL,
  `Text` TEXT NULL,
  `Created_at` DATETIME NULL,
  PRIMARY KEY (`NotificationID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `PaySprintCred` (
  `PaySprintCredID` INT AUTO_INCREMENT NOT NULL,
  `ClientID` VARCHAR(50) NULL,
  `ClientSecrate` VARCHAR(300) NULL,
  `PaySprintKey` VARCHAR(50) NULL,
  `PaySprintIV` VARCHAR(50) NULL,
  `IsActive` INT NULL,
  `CreatedOn` DATETIME NULL,
  `UserID` INT NULL,
  `VPAUser` VARCHAR(50) NULL,
  PRIMARY KEY (`PaySprintCredID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `PAYTARAcredMST` (
  `PAYTARACredID` INT AUTO_INCREMENT NOT NULL,
  `SID` VARCHAR(20) NOT NULL,
  `merchantId` VARCHAR(100) NOT NULL,
  `channel` VARCHAR(100) NOT NULL,
  `Token` VARCHAR(1000) NOT NULL,
  `Createdon` DATETIME NOT NULL,
  `ActiveFlag` INT NULL,
  PRIMARY KEY (`PAYTARACredID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Service_Payout` (
  `Service` VARCHAR(50) NULL,
  `AllowSevice` INT NULL,
  `ServiceID` INT AUTO_INCREMENT NOT NULL,
  PRIMARY KEY (`ServiceID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SIDcreds` (
  `PipeID` INT AUTO_INCREMENT NOT NULL,
  `SID` VARCHAR(50) NULL,
  `ClientID` VARCHAR(500) NULL,
  `ClientSecret` VARCHAR(500) NULL,
  `Checksum` VARCHAR(5000) NULL,
  `ActiveFlag` INT NULL,
  PRIMARY KEY (`PipeID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `User_Tax_Mst` (
  `ID` INT AUTO_INCREMENT NOT NULL,
  `Tax` DECIMAL(18, 2) NULL,
  `UserID` VARCHAR(50) NULL,
  `Pay_Tax` DECIMAL(18, 2) NULL,
  `MinimumPayoutAmount` INT NULL,
  `RupessCharge` DECIMAL(18, 2) NULL,
  `MaximumPayoutAmount` INT NULL,
  `FlatRate` INT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `UserMaster` (
  `UserId` INT AUTO_INCREMENT NOT NULL,
  `Name` VARCHAR(200) NULL,
  `BusinessName` VARCHAR(200) NULL,
  `Mobile` VARCHAR(15) NULL,
  `EmailId` VARCHAR(100) NULL,
  `Gender` CHAR(1) NULL,
  `Dob` VARCHAR(50) NULL,
  `PAN` VARCHAR(10) NULL,
  `Pincode` VARCHAR(6) NULL,
  `Address` VARCHAR(200) NULL,
  `City` VARCHAR(100) NULL,
  `State` VARCHAR(100) NULL,
  `GSTNo` VARCHAR(16) NULL,
  `Status` SMALLINT NULL,
  `CreatedOn` DATETIME NULL,
  `Password` VARCHAR(20) NULL,
  `Wallet_Limit` INT NULL,
  `Available_Amount` DECIMAL(10, 2) NULL,
  `Collection_Amount` DECIMAL(18, 2) NULL,
  `ifsc` VARCHAR(50) NULL,
  `Account` VARCHAR(50) NULL,
  `Hold_Amt` DECIMAL(18, 2) NULL,
  `SID` VARCHAR(100) NULL,
  `AgentID` VARCHAR(50) NULL,
  `payout_flag` INT NULL,
  `Callback_URL` VARCHAR(1000) NULL,
  `Payin_Chnl` VARCHAR(20) NULL,
  `Payout_Url` VARCHAR(1000) NULL,
  `ClientID` VARCHAR(50) NULL,
  `ClientSecret` VARCHAR(50) NULL,
  `RTSettlementOn` INT NULL,
  `FailedCount` INT NULL,
  `Business_Type` VARCHAR(10) NULL,
  `Business_Category` VARCHAR(2000) NULL,
  `Business_Sub_Category` VARCHAR(2000) NULL,
  `WebAppURL` VARCHAR(2000) NULL,
  `BankName` VARCHAR(500) NULL,
  `AccountHolderName` VARCHAR(500) NULL,
  `RequestHashKey` VARCHAR(100) NULL,
  `RequestSaltKey` VARCHAR(100) NULL,
  `RequestAESKey` VARCHAR(100) NULL,
  `ResponseHashKey` VARCHAR(100) NULL,
  `ResponseSaltKey` VARCHAR(100) NULL,
  `ResponseAESKey` VARCHAR(100) NULL,
  `UpdatedWebhookFlag` INT NULL,
  `UpdatedWebhookCreationTime` DATETIME NULL,
  `UpdatedApiKeyFlag` INT NULL,
  `UpdatedApiKeyCreationTime` DATETIME NULL,
  `UserType` INT NULL,
  `PayoutServiceID` INT NULL,
  `CCAvenueMID` VARCHAR(100) NULL,
  `CCAvenueWorkingKey` VARCHAR(200) NULL,
  `CCAvenueAccessCode` VARCHAR(100) NULL,
  `IPWhilteListed` INT NULL,
  `InnerPayinFlag` INT NULL,
  PRIMARY KEY (`UserId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=50000;

-- default constraints
ALTER TABLE `AgentMst` ALTER COLUMN `MobileNumber` SET DEFAULT ((0));
ALTER TABLE `IpWhitelistMst` ALTER COLUMN `Created_On` SET DEFAULT (CURRENT_TIMESTAMP);
ALTER TABLE `IpWhitelistMst` ALTER COLUMN `Status` SET DEFAULT ((1));
ALTER TABLE `MONEY_TRANSFER_PAYIN` ALTER COLUMN `TRUpdated` SET DEFAULT ((0));
ALTER TABLE `MONEY_TRANSFER_PAYIN` ALTER COLUMN `UpdatedBalance` SET DEFAULT ((0));
ALTER TABLE `Notifications` ALTER COLUMN `Created_at` SET DEFAULT (CURRENT_TIMESTAMP);
ALTER TABLE `PaySprintCred` ALTER COLUMN `IsActive` SET DEFAULT ((1));
ALTER TABLE `PaySprintCred` ALTER COLUMN `CreatedOn` SET DEFAULT (CURRENT_TIMESTAMP);
ALTER TABLE `PAYTARAcredMST` ALTER COLUMN `Createdon` SET DEFAULT (CURRENT_TIMESTAMP);
ALTER TABLE `PAYTARAcredMST` ALTER COLUMN `ActiveFlag` SET DEFAULT ((1));
ALTER TABLE `SIDcreds` ALTER COLUMN `ActiveFlag` SET DEFAULT ((1));
ALTER TABLE `User_Tax_Mst` ALTER COLUMN `MinimumPayoutAmount` SET DEFAULT ((300));
ALTER TABLE `User_Tax_Mst` ALTER COLUMN `RupessCharge` SET DEFAULT ((10));
ALTER TABLE `User_Tax_Mst` ALTER COLUMN `MaximumPayoutAmount` SET DEFAULT ((150000));
ALTER TABLE `User_Tax_Mst` ALTER COLUMN `FlatRate` SET DEFAULT ((0));
ALTER TABLE `UserMaster` ALTER COLUMN `CreatedOn` SET DEFAULT (CURRENT_TIMESTAMP);
ALTER TABLE `UserMaster` ALTER COLUMN `Available_Amount` SET DEFAULT ((0));
ALTER TABLE `UserMaster` ALTER COLUMN `Collection_Amount` SET DEFAULT ((0));
ALTER TABLE `UserMaster` ALTER COLUMN `Hold_Amt` SET DEFAULT ((0));
ALTER TABLE `UserMaster` ALTER COLUMN `AgentID` SET DEFAULT ((1));
ALTER TABLE `UserMaster` ALTER COLUMN `RTSettlementOn` SET DEFAULT ((1));
ALTER TABLE `UserMaster` ALTER COLUMN `FailedCount` SET DEFAULT ((0));
ALTER TABLE `UserMaster` ALTER COLUMN `UpdatedWebhookFlag` SET DEFAULT ((0));
ALTER TABLE `UserMaster` ALTER COLUMN `UpdatedApiKeyFlag` SET DEFAULT ((0));
ALTER TABLE `UserMaster` ALTER COLUMN `UserType` SET DEFAULT ((1));
ALTER TABLE `UserMaster` ALTER COLUMN `PayoutServiceID` SET DEFAULT ((8));
ALTER TABLE `UserMaster` ALTER COLUMN `IPWhilteListed` SET DEFAULT ((1));
ALTER TABLE `UserMaster` ALTER COLUMN `InnerPayinFlag` SET DEFAULT ((0));
